[project]
name = "process-card-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docxtpl>=0.20.2",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "pywin32>=311",
    "streamlit[pdf]>=1.53.1",
]
